### PR TITLE
Dev2

### PR DESCRIPTION
**Pull request by ideologysec**
- based off of dev branch, because I'm new at git, and couldn't squash master+dev into dev2

Changes:
- Added scored or notscored to all rule plays.
- Added rule tags to all rules (I think)
- Added 5.5 and 5.6 to defaults/main.yml
- added section tags to tasks/main.yml for easy section testing
- cleaned up tasks/post.yml for easy reading + task header standardization; removed "when == Debian" since this is only for Ubuntu systems
- standardized order of tags (levels, scored, patch, subsystem, rule, notimplemented).
- added cron, sshd, ntp, syslog, filesystems and maybe several other tags to various plays to allow bypassing or enabling based on subsystem (mostly section 5)
- moved udf & squashfs to proper rule numbers, and added FAT (Section 1)
- moved multiple plays for the same rule into a single block (block names are only supported >= Ansible 2.3). This allows for a single "when" to run the entire block, and for nicer code folding. Unfortunately, it does push the minimum requirement from 2.1 -> 2.3; I will look at block syntax without names if backwards compat that far is desired.
- updated the initial checks to explicitly check for Ubuntu 16.04 and fail if not, rather than running successfully on 14.04 because "not RedHat"
- switched "restart auditd" to be service-based instead of a command command; this is more Ansible-y and works on both RedHat and Debian families, with both SysV init and systemd init services. This also tracks with redhat-cis if we care about upstream.
- removed extraneous 1.1.2 rule, since it did nothing that calling notify: systemd restart tmp.mount didn't do already
- updated regexp in 1.1.1.x to match properly now; it was not catching existing lines if it had been run once. also added "state: present" to lineinfile for 1.1.1.1 so it creates the CIS.conf file
- fixed rule 4.1.6 template to conform to the Ubuntu CIS benchmark instead of the RedHat one
- removed as many "when: Debian" references as possible to clean this all up (since the check for the OS version got reworked, and it was nominally unneccessary anyway)

### CODE REVIEW

**Comment by florianutz** [comment]
I merged your pull request #12 into the Dev branch. It looks like all your work was also in this pull request. There is a conflict between dev and master which need be fixed by me first. Are you ok when I close this pull request without merging into the master branch? I'm right that all your work in the other request is?

**Comment by ideologysec** [comment]
You are correct, and more than welcome to close this pull request without merging - all of my work did end up in #12

**Comment by florianutz** [comment]
Thanks a lot for your work!
Currently I am looking for an solution for an idempotence issue anounced by travis-ci and molecule.

ERROR: Idempotence test failed because of the following tasks:
* [instance] => Ubuntu1604-CIS : SCORED | 1.1.1.4 | PATCH | Ensure mounting of hfs filesystems is disabled
* [instance] => Ubuntu1604-CIS : SCORED | 1.1.1.5 | PATCH | Ensure mounting of hfsplus filesystems is disabled
* [instance] => Ubuntu1604-CIS : NOTSCORED | 4.3 | PATCH | Ensure logrotate.conf exists

**Comment by ideologysec** [comment]
Very strange, especially since the regex is the same for all of the rest of the filesystem modules that are not failing the idempotence test. Ansible-lint didn't even flag those as problematic (not that it's necessarily going to find things like this, of course).

**Comment by florianutz** [comment]
Yes it is really strange. I try to reproduce the error on a virtual machine. Molecule runs in a Docker container  and sometimes makes weird things ;)

**Pull request closed without merging**
